version: '3'

services:
  node0:
    container_name: node0
    image: "tepleton/tondnode"
    ports:
      - "46656-46657:46656-46657"
    environment:
      - ID=0
      - LOG=$${LOG:-tond.log}
    volumes:
      - ./build:/tond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  node1:
    container_name: node1
    image: "tepleton/tondnode"
    ports:
      - "46659-46660:46656-46657"
    environment:
      - ID=1
      - LOG=$${LOG:-tond.log}
    volumes:
      - ./build:/tond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  node2:
    container_name: node2
    image: "tepleton/tondnode"
    environment:
      - ID=2
      - LOG=$${LOG:-tond.log}
    ports:
      - "46661-46662:46656-46657"
    volumes:
      - ./build:/tond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  node3:
    container_name: node3
    image: "tepleton/tondnode"
    environment:
      - ID=3
      - LOG=$${LOG:-tond.log}
    ports:
      - "46663-46664:46656-46657"
    volumes:
      - ./build:/tond:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

